packages:
  - apps/*
  - packages/*
  - frontend
  - backend
  - backend-e2e

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - oxc-resolver
  - sharp
  - unrs-resolver
